
name: Main

on: push

jobs:
  run-linters-and-test:
    name: Format Code
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
      
      - name: Format Go Code
        run: gofmt -w .

      - name: Run go vet
        run: go vet . github.com/jordan-bonecutter/purplecrayon/svg

      - name: Run go lint
        uses: Jerome1337/golint-action@v1.0.2
        with:
          golint-path: '. svg'

      - name: Run Go Test
        run: go test .

      - name: Commit linter changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: LinterBot
          commit_message: Linter found style changes
